### ISSUE TITLE
Lỗi nút save changes

### ISSUE THREAD

**Issue by elio-perlman-13** [grintondh/LearningSystem#10]
Khi lưu câu hỏi được import thì có lỗi này

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index is less than 0. (Parameter 'index')
  Source=Newtonsoft.Json
  StackTrace:
   at Newtonsoft.Json.Linq.JContainer.RemoveItemAt(Int32 index)
   at Learning_System.EditQuestionForm.AddNewQuestionForm_SaveBtn_Click(Object sender, EventArgs e) in D:\hust\20222\Lập trình hướng đối tượng\Bài tập lớn\Learning System\Learning System\EditQuestionForm.cs:line 193
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by grintondh** [comment]
System.ArgumentOutOfRangeException
...
Message=Index is less than 0. (Parameter 'index')

Thể hiện index đang lấy nhỏ hơn 0 (mảng, list,...). Có thể debug check xem lỗi ở dòng nào và index lúc đó bằng bao nhiêu.

**Comment by elio-perlman-13** [comment]
![image](https://github.com/grintondh/LearningSystem/assets/129037773/6329a6a4-c6c9-44db-a262-f3899d10c5f5)

**Comment by NgxLama** [comment]
Done
